---
- name: Namespace für die Anwendung
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_root }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: judge
